### ISSUE TITLE
Can't store metrics with ! in name

### ISSUE THREAD

**Issue by grk** [noahhl/batsd#16]
I'm using batsd to store instrumentation form a Rails app. Naturally, some of the methods have a `!` in their name. It looks like this line in the receiver prevents those measurements from being stored:

``` ruby
key, value, type, sample = row.split(/\||:|!/)
```

``` ruby
1.9.3p194 :010 > "test!:1|c".split(/\||:|!/)
 => ["test", "", "1", "c"] 
1.9.3p194 :011 > "test:1|c".split(/\||:|!/)
 => ["test", "1", "c"] 
```

Is it necessary to split on bangs too? I looked into the statsd protocol and cound't find any reason for that. I can make a quick pull request with the changes if this turns out to be a bug.

**Comment by noahhl** [comment]
I can't think of there being a good reason why we're splitting on bangs. Etsy's "reference" implementation doesn't either.

A pull request would be greatly appreciated and promptly accepted.

**Comment by grk** [comment]
Made a pull request in #17. There probably is a way on github to merge the pull into this issue...

**Comment by noahhl** [comment]
Thanks!
