### ISSUE TITLE
Feature: Delete metrics by key

### ISSUE THREAD

**Issue by groe** [noahhl/batsd#18]
First of all: Great work! I have been using batsd for some months now and it works great for me.

I just wanted to clean up in my batsd database and remove old metrics that are not interesting to me anymore and noticed that that's actually harder than I thought: I would have to delete the corresponding keys in redis-cli (DEL command), and then figure out what data files belong to that metric. Therefore I would have to build MD5 hashes for the metric name and all rentention keys, check if each file exists, and if it does delete it. If the containing directory is empty then, I'd like to delete that too.

I think something like `./bin/batsd delete <key>` would be really nice to simplify things. Another way might be to extend the management interface on port 8126 by this 'delete' function. What do you guys think about that?

**Comment by noahhl** [comment]
Great idea!

Adding a `delete` command to `bin/batsd` would be great. Something about exposing delete over the management interface makes me a little uneasy on first pass, but maybe it would be ok.

I'll add this the next time I'm at work on this, or a pull request would be more than welcome.

Glad to hear batsd's been working well for you!

**Comment by grk** [comment]
Yup, this could be useful. Also, the delete command could accept a date range so that we can remove only part of a series. I might get a pull request for that this weekend, someone at work also requested this.

**Comment by groe** [comment]
Nice to hear that this is something we will see in batsd soon!

@grk Are you working on it already? Otherwise I could try to get something up running too.

**Comment by grk** [comment]
@groe haven't yet started, go ahead if you like :)

**Comment by groe** [comment]
Here we go: #19 :-)
