### ISSUE TITLE
Are there any plans to release a frontend to this, similar to Graphite?

### ISSUE THREAD

**Issue by cmer** [noahhl/batsd#22]

**Comment by cmer** [comment]
Since you said "soon" 237 days ago! :) http://news.ycombinator.com/item?id=4044432

**Comment by noahhl** [comment]
Hm, 237 days isn't "soon"? ;)

Yes, still planning on it, but no real time frame at this point.

You might try https://github.com/mikeycgto/batsd-dash. I haven't personally used it, but know it's actively maintained.

**Comment by cmer** [comment]
What would be an effective way to pressure you into releasing this in the next couple of weeks?

What if I buy you a puppy? or a poney?

**Comment by cmer** [comment]
Seriously, it'd be really appreciated and useful for us. If that's possible at all.

**Comment by xinuc** [comment]
We'd really appreciate if you can release this too :smile: 

it have been "711 days ago" btw :grin:
