### ISSUE TITLE
Links to documentation are dead

### ISSUE THREAD

**Issue by bguthrie** [noahhl/batsd#23]
I'm getting a 404 when I hit any of the documentation pages - is it just me?

**Comment by noahhl** [comment]
Woops, not you - I screwed with DNS and didn't consider those links. I'll fix.

**Comment by noahhl** [comment]
Should be fixed now (though the documentation in the `dev` branch where active work is happening is woefully out of date; will fix before merging).

**Comment by bguthrie** [comment]
Looks good now. Thanks Noah!
