### ISSUE TITLE
Lots of CLOSE_WAIT connections to redis lying around

### ISSUE THREAD

**Issue by jjrussell** [noahhl/batsd#24]
I am seeing a large number of CLOSE_WAIT connections to redis (on the same box) left open by the batsd-server process. I don't see anything in the code that would explicitly call `@redis.quit` on the redis connections that are opened in `Server#post_init`. 

Under what circumstances would the server process clean up these connections.  We've been seeing the server hang after periods of a day or two of uptime. I'm wondering if this is related. 

Thanks.

**Comment by noahhl** [comment]
Yep, this is totally a bug - the server isn't closing connections when it should be. You'll often see this as a "Too many open files error".

I fixed it on the dev branch a couple months ago, but haven't yet merged that to master (it involves some format changes in the underlying storage of data, which I still need to properly document the migration pathway for).

I just plucked that change into master in https://github.com/noahhl/batsd/commit/d13e9a37f8feb118a9670281413309aae1e9d9f7. Mind giving that a try and  seeing if it helps?

**Comment by jjrussell** [comment]
Now that's service.  I'll give it a ride and let you know.  Thanks.

**Comment by jjrussell** [comment]
Clean as a whistle.  Thanks for the crazy fast response.

**Comment by noahhl** [comment]
Sure thing!
