### ISSUE TITLE
JRuby JSON LoadError

### ISSUE THREAD

**Issue by mjc-gh** [noahhl/batsd#7]
Using RVM off a fresh jruby install I get a `LoadError` on the json gem when running:

```
bundle exec ruby --1.9 bin/batsd -c config.yml
```

This is using jruby-1.6.5 but I've also tried jruby-head with the same results.

**Comment by noahhl** [comment]
Fixed in 8f3e5dc47eed3516606760a0d4fbe1c2d2dbd7d5. Thanks!

**Comment by mjc-gh** [comment]
Awesome, works fine in dev and production now. Thanks!
